#!/usr/bin/env tclsh

package require Tcl 8.6

proc readfile fn {
	set h	[open $fn r]
	try {
		read $h
	} finally {
		close $h
	}
}

lassign $argv cmd callgraphs_fn

proc callgraphs_fn {} {
	global callgraphs_fn

	if {$callgraphs_fn ne ""} {
		return $callgraphcs_fn
	}

	set dir	[file dirname [file normalize [info script]]]
	while {$dir ne "/"} {
		if {[file readable [file join $dir callgraphs]]} {
			return [file join $dir callgraphs]
		}
		set dir	[file dirname $dir]
	}
	error "No callgraph lookup file found"
}

set callgraphs	[readfile [callgraphs_fn]]

foreach caller [dict get $callgraphs calledby $cmd] {
	foreach callrec [lmap c [dict get $callgraphs calls $caller] {
		if {[lindex $c 0] ne $cmd} continue
		set c
	}] {
		lassign $callrec caller_cmd fn f_line f_char t_line t_char
		puts [list $caller_cmd $fn $f_line $f_char $t_line $t_char]
	}
}

