#!/usr/bin/env tclsh

proc readfile fn {
	set h	[open $fn r]
	set dat	[read $h]
	close $h
	return $dat
}

lassign $argv cmd callgraphs_fn

proc callgraphs_fn {} {
	global callgraphs_fn

	if {$callgraphs_fn ne ""} {
		return $callgraphcs_fn
	}

	set dir	[pwd]
	while {$dir ne "/"} {
		set candidate	[file join $dir callgraph]
		if {[file readable $candidate]} {
			return $candidate
		}
		set dir	[file dirname $dir]
	}
	error "No callgraph lookup file found"
}

set callgraphs	[readfile [callgraphs_fn]]

dict for {caller callrecs} [dict get $callgraphs $cmd] {
	foreach callrec $callrecs {
		lassign $callrec fn f_line f_char t_line t_char
		puts [list $caller $fn $f_line $f_char $t_line $t_char]
	}
}

